#!/usr/bin/env bash

# Test the currently built release of Ksilorama from the dist/ dir.
# Run this before making a release.
#
# This should be run on Windows, because Ksilorama is mostly a no-op elsewhere.
# Hmmm, this script should probably be a .bat file then? Nah, WSL FTW.
#
# Uploads package from the dist/ directory to the *test* PyPI.
# Create a fresh virtualenvironment and install ksilorama from test PyPI.
# Import Ksilorama and make trivial use of it.

# Exit on error
set -eu -o pipefail

syspython=python3
bin="$HOME/.virtualenvs/ksilorama/bin"
sandbox=test-release-playground

# Upload to the test PyPI.
$bin/twine upload --repository ksilorama-test dist/ksilorama-* \
    || echo "  > Expect a 400 if package was already uploaded."

# cd elsewhere so we cannot import from local source.
mkdir -p $sandbox
(
    # Create a temporary disposable virtualenv.
    $syspython -m venv --clear $sandbox/venv

    # voodoo sleep. I saw the following install fail, due to expected version
    # not being listed at test.pypi.org, but then a few seconds later, re-run
    # manually, it worked fine.
    sleep 5

    version=$(grep __version__ ksilorama/__init__.py | cut -d' ' -f3 | tr -d "'")

    cd $sandbox

    # Install the package we just uploaded.
    # (--extra-index-url for this project's requirements)
    venv/bin/python -m pip --quiet install --index-url https://test.pypi.org/simple --extra-index-url https://pypi.org/simple ksilorama==$version

    # Import and use Ksilorama from the temp virtualenv.
    venv/bin/python -c "import ksilorama; ksilorama.init(); print(ksilorama.Fore.GREEN + \"OK: Ksilorama\", ksilorama.__version__, \"from test pypi install.\")"
)

# Tidy up
rm -rf $sandbox
